### ISSUE TITLE
Package in the AUR

### ISSUE THREAD

**Issue by TheJackiMonster** [varmd/wayward#1]
Do you plan on providing a package in the AUR as well? I mean it's easy to build the package via PKGBUILD from source cloning the repository but this could be automated using an AUR-helper. I think the PKGBUILD would only need a source attribute for a wayward-git package.

**Comment by varmd** [comment]
There are prebuilt binaries in the Releases. It also takes couple of seconds to build with few dependencies. And it is pretty stable as I have been using it for several years already with very few crashes. 

So there is little need for AUR and I can't support it since I don't use AUR helpers.

**Comment by TheJackiMonster** [comment]
Because I personally prefer using an AUR helper, I have created a package now: https://aur.archlinux.org/packages/wayward-git/

However it does not install the binaries but it builds from source because I don't like manually replacing urls to the binaries each release. I just thought a package updating process could be integrated into the release process. But I don't think it's necessary.

Anyway keep up the great work.
