### ISSUE TITLE
hide-app config

### ISSUE THREAD

**Issue by scruffidog** [varmd/wayward#11]
if I'm understanding the purpose correctly, the hide-app config essentially blacklists items from: 

/usr/share/applications/*.desktop

and builds [launcher] entries, without the need to hard-code them in weston.ini ?

Is there any facilities for regular expressions/wildcards/globbing ? A quick test using * seems to indicate no support for it.

So, some questions:
Is there a magic invocation/key word to disable the auto-magical entry generation (ie hide-apps=ALL, etc) ?
It also looks like there are some hard-coded entries (battery/power, running app list, date/time, volume, etc), are any of them configurable to run a different app ? (ie for volume, run pavucontrol, etc)
Is there any way to enable like a text tool-tip popup when hovering over the icons ?  The current implementation has issues when the desktop file icon entry points to something that does not exist or is not visually intuitive to function. Problematic icons shows a generic placeholder icon so it is difficult to see what is app it really is. And obviously mucking with the actual desktop entries is only a stopgap solution until the next pkg update.

In any event, this is such a efficient compositor that is a pleasure to use so not complaining at all...

**Comment by CristobalRR** [comment]
Same problem here, too crowded bar, need wild card to wipe all entrances and assing them manually with the vanilla weston launcher, i think a better idea would be to create a entrance to enable or dissable the auto-magical entry generation

**Comment by varmd** [comment]
hide-app just hides apps that do not have "NoDisplay" in /usr/share/applications/app.desktop.
Not sure what auto-magical entry generation refers to.

If you are referring to an option to disable adding apps from /usr/share/applications/*.desktop that can be added in future releases.

**Comment by varmd** [comment]
Added
