### ISSUE TITLE
The build script fails due to hardcoding

### ISSUE THREAD

**Issue by TheJackiMonster** [varmd/wayward#12]
Weston 12.0.0 got released which changed the path of the includes. However wayward uses 11 instead of 12 which is hardcoded into the build.sh script. I think that should be changed. Either it should be possible to override `WESTON_VER` from outside the build script or even more convenient the script could just utilize `pkgconf` to automatically pick the proper include paths, library names and cflags.

```
pkgconf --cflags --libs weston cairo wayland-client wayland-cursor libpng alsa libjpeg xkbcommon
```

**Comment by varmd** [comment]
That's not possible since Weston breaks API with new releases.

**Comment by TheJackiMonster** [comment]
In that case it might make sense to include the required Weston version as git submodule for building. Otherwise depending on the distribution and its repositories building requires looking up release tarballs depending on config files.
