### ISSUE TITLE
cannot stat '../source': No such file or directory

### ISSUE THREAD

**Issue by fractal-fumbler** [varmd/wayward#3]
Hello :)
found out recently about wayward and tried to compile it on archlinux and encountered following errors when makepkg is preparing package:
```
==> Starting prepare()...
cp: cannot stat '../source': No such file or directory
==> ERROR: A failure occurred in prepare().
    Aborting...
```
Since i set different variable (/tmp/makepkg) for BUILDDIR in makepkg.conf, so i slightly modified PKGBUILD:
```
export _source="$PWD"
prepare() {
  cd "$srcdir/"
  rm -rf $srcdir/source
  cp -r "$_source"/source .
}
```

**Comment by varmd** [comment]
Added to PKGBUILD
