### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by scruffidog** [varmd/wayward#8]
Latest update on Arch (testing)
tried to starup by running weston on commandline (first by copying /etc/xdg/weston/weston.ini to ~/.config when that crashed,  deleting ~/.config/weston.ini), nothing seems to work. According to attached log, trying to run something that does not exist on my system ?

[wayward.log](https://github.com/varmd/wayward/files/8718923/wayward.log)

**Comment by varmd** [comment]
Based on the log probably alsa sound setup is broken.
